name: CarServiceCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        ftp_server: 127.0.0.1
        ftp_username: gyan
        ftp_password: 3690
        remote_dir: /home/gyan/Desktop
